name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Install Poetry
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-in-project: true

      # Install dependencies
      - name: Install dependencies
        run: make install

      # Run linting
      - name: Lint code
        run: make lint

      # Run tests
      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}   # <-- add repo root to PYTHONPATH
        run: make test
